export const OMNIROUTE_RESPONSE_HEADERS = {
  cache: "X-AI-Gate-Cache",
  cacheHit: "X-AI-Gate-Cache-Hit",
  compression: "X-AI-Gate-Compression",
  costSaved: "X-AI-Gate-Cost-Saved",
  decision: "X-AI-Gate-Decision",
  fallbackAttempts: "X-AI-Gate-Fallback-Attempts",
  latencyMs: "X-AI-Gate-Latency-Ms",
  model: "X-AI-Gate-Model",
  progress: "X-AI-Gate-Progress",
  provider: "X-AI-Gate-Provider",
  requestId: "X-AI-Gate-Request-Id",
  responseCost: "X-AI-Gate-Response-Cost",
  tokensIn: "X-AI-Gate-Tokens-In",
  tokensOut: "X-AI-Gate-Tokens-Out",
  version: "X-AI-Gate-Version",
} as const;
