/**
 * postgresAdapter.ts — PostgreSQL adapter implementing the uniform async
 * DatabaseAdapter interface (Phase 2.8 / pg-3).
 *
 * PostgreSQL is a network service with an async-only driver, so this adapter
 * is natively async (no sync-boxing needed). Every statement runs through
 * `translateSqliteToPostgres` so business modules keep writing SQLite-flavoured
 * SQL. `raw` is intentionally unusable here: the sync-probe paths that use it
 * are SQLite-only (see core.ts / getDbInstance).
 *
 * Transactions are connection-bound: `transaction()` borrows a client from the
 * pool for the duration of the callback, and every statement executed inside
 * the callback (including nested transactions via SAVEPOINT) routes to that
 * client through AsyncLocalStorage.
 */
import { AsyncLocalStorage } from "node:async_hooks";
import pg from "pg";
import BetterSqlite3 from "better-sqlite3";
import type { DatabaseAdapter, DatabaseDriver, PreparedStatement, RunResult } from "./types";
import { pragmaToQuery, sqliteMasterToQuery, translateSqliteToPostgres } from "./postgresDialect";

const { Pool } = pg;

/** Lazy in-memory SQLite scratch handle for PG-mode `.raw` degradation. */
let scratchRaw: BetterSqlite3.Database | null = null;

/**
 * node-pg returns BIGINT (int8, OID 20) and INTEGER (int4, OID 23) columns as
 * *strings* by default (`"1"`), to avoid numeric precision loss on values that
 * exceed Number.MAX_SAFE_INTEGER. SQLite (the other driver) returns real
 * numbers for the same columns, and business modules compare with strict
 * equality (`=== 1`, `=== 0`). The string/`=== number` mismatch silently
 * breaks every boolean flag stored as an integer (e.g. services.enabled,
 * services.proxied → `"1" === 1` is false → service judged disabled).
 *
 * We register parsers that return JS numbers for int8/int4 (and their
 * serial aliases). Column types generated by our own SQLite→PG migration are
 * BIGINT or INTEGER — none legitimately exceed 2^53-1 (ids, token counts,
 * timestamps fit comfortably), so numeric conversion is lossless here. This is
 * a deliberate, project-wide contract: PG must behave like SQLite's numeric
 * columns so driver-agnostic modules need no per-module coercion.
 */
for (const oid of [20, 21, 23, 26]) {
  // int8 / int2 / int4 / oid
  pg.types.setTypeParser(oid, (v: string) => (v === null ? null : parseInt(v, 10)));
}

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/**
 * Build the call-site param normaliser (array | named object → positional array)
 * for a given translated SQL, AND produce the positional-SQL in which named
 * SQLite placeholders (@name / :name) were rewritten to $N. The `?` placeholders
 * were already numbered by the dialect layer; named ones are appended after them.
 * The PG cast operator `::type` is excluded via negative lookbehind so
 * `to_char((ts)::timestamptz ...)` survives untouched. Returns both so the caller
 * can (a) execute the positional SQL and (b) map object args onto that order.
 */
function buildBinder(translatedSql: string): {
  sql: string;
  bind: (params: unknown[]) => unknown[];
} {
  let maxPositional = 0;
  const positionalMatch = translatedSql.match(/\$(\d+)/g);
  if (positionalMatch) {
    for (const m of positionalMatch) {
      maxPositional = Math.max(maxPositional, Number(m.slice(1)));
    }
  }
  const namedOrder: string[] = [];
  const sql = translatedSql.replace(/(?<!:)[@:]([a-zA-Z_][a-zA-Z0-9_]*)/g, (_m, name) => {
    namedOrder.push(name);
    return `$${++maxPositional}`;
  });

  const bind = (params: unknown[]): unknown[] => {
    if (namedOrder.length > 0 && params.length === 1 && isPlainObject(params[0])) {
      const obj = params[0] as Record<string, unknown>;
      return namedOrder.map((name) => obj[name]);
    }
    if (params.length === 1 && isPlainObject(params[0])) {
      // No named placeholders but an object was passed (better-sqlite3
      // allows named params with object args) — map by object keys only if
      // the SQL actually contains them; otherwise drop empty objects.
      const keys = Object.keys(params[0] as Record<string, unknown>);
      return keys.length === 0 ? [] : params;
    }
    return params;
  };
  return { sql, bind };
}

export interface PostgresAdapterConfig {
  connectionString?: string;
  host?: string;
  port?: number;
  database?: string;
  user?: string;
  password?: string;
  ssl?: boolean | Record<string, unknown>;
  /** Max concurrent clients (default 10). */
  max?: number;
}

/** Carries the transaction-scoped client for the current async context. */
const txStorage = new AsyncLocalStorage<pg.PoolClient>();

/**
 * Primary-key cache: table name → PK column names (insertion order). Warmed
 * once at startup from information_schema so `INSERT OR REPLACE` upserts can
 * emit a valid PG `ON CONFLICT (<pk>) DO UPDATE SET ...` arbiter target.
 */
const pkCache = new Map<string, string[]>();

async function warmPrimaryKeyCache(pool: pg.Pool): Promise<void> {
  const res = await pool.query(
    `SELECT tc.table_name AS table_name, kcu.column_name AS column_name
       FROM information_schema.table_constraints tc
       JOIN information_schema.key_column_usage kcu
         ON tc.constraint_name = kcu.constraint_name
        AND tc.table_schema = kcu.table_schema
        AND tc.constraint_schema = kcu.constraint_schema
      WHERE tc.constraint_type = 'PRIMARY KEY'
        AND tc.table_schema = 'public'
      ORDER BY tc.table_name, kcu.ordinal_position`
  );
  pkCache.clear();
  for (const row of res.rows as Array<{ table_name: string; column_name: string }>) {
    const list = pkCache.get(row.table_name) ?? [];
    list.push(row.column_name);
    pkCache.set(row.table_name, list);
  }
}

function arbiterFor(table: string): string[] | undefined {
  return pkCache.get(table);
}

export function createPostgresAdapter(config: PostgresAdapterConfig = {}): DatabaseAdapter {
  const pool = new Pool({
    connectionString: config.connectionString,
    host: config.host,
    port: config.port,
    database: config.database,
    user: config.user,
    password: config.password,
    ssl: config.ssl,
    max: config.max ?? 10,
  });

  let closed = false;

  /**
   * Per-instance warm guard for the PRIMARY-KEY cache.
   *
   * `pkCache` is module-scoped, and this module is bundled into MULTIPLE webpack
   * chunks (it is pulled in both by the bootstrap/instrumentation chunk and by
   * API-route chunks), so each copy keeps its OWN pkCache Map. `initDatabaseDriver`
   * only warms whichever copy it was bundled with — a route that imports this
   * module through a different chunk may hold a cold pkCache, in which case
   * `INSERT OR REPLACE` silently degrades to `ON CONFLICT DO NOTHING` (existing
   * keys are never updated — the root cause of provider-limits cache writes not
   * persisting). To make every instance self-sufficient we warm lazily on first
   * use, memoised so a single instance only ever queries information_schema once.
   */
  let warmPromise: Promise<void> | null = null;
  function ensurePkWarmed(): Promise<void> {
    if (!warmPromise) {
      warmPromise = warmPrimaryKeyCache(pool).catch((err) => {
        // Drop the memo on failure so a transient error can be retried later.
        warmPromise = null;
        throw err;
      });
    }
    return warmPromise;
  }
  // Kick off the warm immediately (fire-and-forget) so the common case — a
  // route request arriving after boot — finds the cache already populated.
  void ensurePkWarmed();

  /** True when the given SQLite SQL is an `INSERT OR REPLACE` upsert. */
  function isInsertOrReplace(sql: string): boolean {
    return /\bINSERT\s+OR\s+REPLACE\s+INTO\b/i.test(sql);
  }

  /**
   * Translate `INSERT OR REPLACE` against the CURRENT pkCache. Returns the
   * translated SQL; callers that need a correct arbiter can await ensurePkWarmed()
   * first and re-translate.
   */
  function translateInsertOrReplace(sql: string): string {
    return translateSqliteToPostgres(sql, arbiterFor);
  }

  function clientFor(pool: pg.Pool): pg.PoolClient | pg.Pool {
    return txStorage.getStore() ?? pool;
  }

  return {
    driver: "postgres" as DatabaseDriver,

    /** Internal: warm the PK cache (called by initDatabaseDriver at boot). */
    async __warmPrimaryKeys(): Promise<void> {
      await warmPrimaryKeyCache(pool);
    },

    get open() {
      return !closed;
    },

    get name() {
      return config.database ?? config.connectionString ?? "postgres";
    },

    prepare(sql: string): PreparedStatement {
      // PRAGMA table_info(...) is queried through prepare() by schema helpers —
      // route it to the information_schema translation before the dialect layer.
      const pragmaQ = pragmaToQuery(sql);
      if (pragmaQ) {
        return {
          async run(): Promise<RunResult> {
            const res = await clientFor(pool).query(pragmaQ.sql, pragmaQ.params);
            return { changes: res.rowCount ?? 0, lastInsertRowid: 0 };
          },
          async get(): Promise<unknown> {
            const res = await clientFor(pool).query(pragmaQ.sql, pragmaQ.params);
            return res.rows[0] ?? undefined;
          },
          async all(): Promise<unknown[]> {
            const res = await clientFor(pool).query(pragmaQ.sql, pragmaQ.params);
            return res.rows;
          },
        };
      }

      const upsert = isInsertOrReplace(sql);
      // First-pass translation against the CURRENT pkCache. If this instance's
      // cache is still cold, an INSERT OR REPLACE degrades to ON CONFLICT DO
      // NOTHING — so for upserts we (a) ensure the cache is warm before the first
      // execution, and (b) re-translate with the warmed cache to emit a real
      // ON CONFLICT (...) DO UPDATE upsert. This makes every webpack copy of this
      // module self-sufficient without depending on initDatabaseDriver having
      // warmed this particular instance.
      const translated = translateInsertOrReplace(sql);
      const needsWarmRetranslate = upsert && /\bON\s+CONFLICT\s+DO\s+NOTHING\b/i.test(translated);

      /** Positional SQL + binder for a given translation. */
      const preparedFor = (t: string) => buildBinder(t);
      const initial = preparedFor(translated);

      /** Final positional SQL + binder, re-translating after the warm when needed. */
      const resolve = (warmed: boolean) =>
        warmed && needsWarmRetranslate ? preparedFor(translateInsertOrReplace(sql)) : initial;

      return {
        async run(...params: unknown[]): Promise<RunResult> {
          if (needsWarmRetranslate) await ensurePkWarmed();
          const { sql: finalSql, bind } = resolve(true);
          const res = await clientFor(pool).query(finalSql, bind(params));
          return {
            changes: res.rowCount ?? 0,
            lastInsertRowid: (res.rows?.[0]?.id as number | bigint | undefined) ?? 0,
          };
        },
        async get(...params: unknown[]): Promise<unknown> {
          if (needsWarmRetranslate) await ensurePkWarmed();
          const { sql: finalSql, bind } = resolve(true);
          const res = await clientFor(pool).query(finalSql, bind(params));
          return res.rows[0] ?? undefined;
        },
        async all(...params: unknown[]): Promise<unknown[]> {
          if (needsWarmRetranslate) await ensurePkWarmed();
          const { sql: finalSql, bind } = resolve(true);
          const res = await clientFor(pool).query(finalSql, bind(params));
          return res.rows;
        },
      };
    },

    async exec(sql: string): Promise<void> {
      const translated = translateSqliteToPostgres(sql, arbiterFor);
      await clientFor(pool).query(translated);
    },

    async pragma(pragmaStr: string, _options?: { simple?: boolean }): Promise<unknown> {
      const q = pragmaToQuery(pragmaStr);
      if (!q) return undefined;
      const res = await clientFor(pool).query(q.sql, q.params);
      return res.rows;
    },

    transaction<T>(fn: (...args: unknown[]) => Promise<T> | T): (...args: unknown[]) => Promise<T> {
      return async (...args: unknown[]): Promise<T> => {
        const outer = txStorage.getStore();
        if (outer) {
          // Nested transaction → SAVEPOINT on the outer client.
          const sp = `sp_${Math.random().toString(36).slice(2, 10)}`;
          await outer.query(`SAVEPOINT ${sp}`);
          try {
            return (await txStorage.run(outer, () => fn(...args))) as T;
          } catch (err) {
            await outer.query(`ROLLBACK TO ${sp}`);
            throw err;
          }
        }
        const client = await pool.connect();
        try {
          await client.query("BEGIN");
          const result = (await txStorage.run(client, () => fn(...args))) as T;
          await client.query("COMMIT");
          return result;
        } catch (err) {
          await client.query("ROLLBACK").catch(() => {});
          throw err;
        } finally {
          client.release();
        }
      };
    },

    async immediate(fn: () => Promise<void> | void): Promise<void> {
      const client = await pool.connect();
      try {
        await client.query("BEGIN");
        await txStorage.run(client, () => fn());
        await client.query("COMMIT");
      } catch (err) {
        await client.query("ROLLBACK").catch(() => {});
        throw err;
      } finally {
        client.release();
      }
    },

    /** PG backups are handled externally (pg_dump) — nothing to do here. */
    async backup(_destination: string): Promise<void> {
      // SQLite file-copy semantics do not apply to a server database.
      return;
    },

    async checkpoint(_mode?: string): Promise<void> {
      // WAL checkpointing is a SQLite concept — no-op for PostgreSQL.
      return;
    },

    async close(): Promise<void> {
      closed = true;
      await pool.end();
    },

    /**
     * PostgreSQL has no synchronous interface. Rather than throwing (which let
     * a single un-migrated sync call site crash the whole process), return a
     * shared in-memory SQLite handle — matching `getDbInstance()`'s PG-mode
     * degradation in core.ts — so sync modules read empty results and churn
     * (schemaColumns, models.dev capabilities) instead of throwing. Warning is
     * surfaced so remaining migrations stay visible. Data written here never
     * persists (scratch-only), exactly like the core.ts fallback.
     */
    get raw(): unknown {
      if (!scratchRaw) {
         
        console.warn(
          "[DB] PostgreSQL has no synchronous driver — returning in-memory SQLite scratch handle. " +
            "Sync .raw call sites hold scratch-only data that will NOT persist to PG."
        );
        scratchRaw = new BetterSqlite3(":memory:");
        // Seed a minimal schema so `prepare(...).get()` on known tables returns
        // empty rows (not "no such table") for defensive call sites. No SCHEMA_SQL
        // import to avoid a circular dependency with core.ts — empty DB is enough
        // for `.raw` degradation (featureFlags/mapCapabilityRecord catch & return
        // undefined on missing tables).
      }
      return scratchRaw;
    },
  } as unknown as DatabaseAdapter;
}

/** Re-export for callers that want to run raw SQLite-master-like queries. */
export { sqliteMasterToQuery };
