/**
 * postgresDialect.ts — SQLite → PostgreSQL dialect translation.
 *
 * Phase 2.8 (pg-3): business modules write SQLite-flavoured SQL; the
 * PostgresAdapter runs every statement through `translateSqliteToPostgres`
 * so modules stay driver-agnostic. Translation is conservative: only known
 * SQLite-only constructs are rewritten, everything else passes through and
 * PostgreSQL itself reports anything it cannot parse.
 *
 * Rewrites (in priority order):
 *   1. `?` placeholders → `$1..$n` (outside string literals / comments)
 *   2. `INSERT OR IGNORE` → `INSERT ... ON CONFLICT DO NOTHING`
 *   3. `INSERT OR REPLACE` / `REPLACE INTO` → `INSERT ... ON CONFLICT DO UPDATE`
 *      (upsert of every column from the VALUES / the conflict target is left
 *      to the caller when a unique key is not inferable)
 *   4. `AUTOINCREMENT` → `GENERATED BY DEFAULT AS IDENTITY`
 *   5. `unixepoch('now')` → `(EXTRACT(EPOCH FROM NOW()))`
 *   6. `datetime('now')` → `NOW()`; `datetime(<expr>)` → `to_timestamp(<expr>)`
 *   7. `strftime('%s', <expr>)` → `EXTRACT(EPOCH FROM <expr>)`
 *   8. `INTEGER PRIMARY KEY` (bare) → `BIGSERIAL PRIMARY KEY`
 *
 * NOT rewritten here (handled by the adapter layer):
 *   - `PRAGMA table_info(x)` / `sqlite_master` — translated to
 *     information_schema queries by the adapter with result-shape mapping.
 */

/** Scan state while rewriting SQL. */
interface Cursor {
  sql: string;
  i: number;
  out: string[];
  paramIndex: number;
  /** Set when we are inside a single/double-quoted string or backticks. */
  quote: "'" | '"' | "`" | null;
}

function isIdentifierChar(ch: string): boolean {
  return /[A-Za-z0-9_$]/.test(ch);
}

/**
 * Rewrite `?` placeholders to `$n`, skipping string literals ('...', "...",
 * `...`) and line/block comments. Returns the rewritten SQL.
 */
function rewritePlaceholders(sql: string): string {
  let quote: "'" | '"' | "`" | null = null;
  let lineComment = false;
  let blockComment = false;
  let n = 0;
  let out = "";

  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    const next = sql[i + 1];

    if (lineComment) {
      out += ch;
      if (ch === "\n") lineComment = false;
      continue;
    }
    if (blockComment) {
      out += ch;
      if (ch === "*" && next === "/") {
        out += "/";
        i++;
        blockComment = false;
      }
      continue;
    }
    if (quote) {
      out += ch;
      if (ch === quote) {
        // Handle doubled quotes inside the literal ('' / "" escapes).
        if (next === quote) {
          out += next;
          i++;
        } else {
          quote = null;
        }
      }
      continue;
    }
    if (ch === "-" && next === "-") {
      lineComment = true;
      out += "--";
      i++;
      continue;
    }
    if (ch === "/" && next === "*") {
      blockComment = true;
      out += "/*";
      i++;
      continue;
    }
    if (ch === "'" || ch === '"' || ch === "`") {
      quote = ch;
      out += ch;
      continue;
    }
    if (ch === "?") {
      n++;
      out += `$${n}`;
      continue;
    }
    out += ch;
  }
  return out;
}

/** Case-insensitive keyword match at cursor position (word boundary). */
function kwAt(sql: string, i: number, kw: string): boolean {
  if (sql.length - i < kw.length) return false;
  if (
    !sql
      .slice(i, i + kw.length)
      .toUpperCase()
      .startsWith(kw)
  )
    return false;
  const before = sql[i - 1];
  const after = sql[i + kw.length];
  const okBefore = before === undefined || !isIdentifierChar(before);
  const okAfter = after === undefined || !isIdentifierChar(after);
  return okBefore && okAfter;
}

/**
 * Rewrite INSERT OR IGNORE / INSERT OR REPLACE / REPLACE INTO to PG upserts.
 * INSERT OR IGNORE → ON CONFLICT DO NOTHING (append at end of statement).
 * INSERT OR REPLACE → ON CONFLICT DO UPDATE SET col=EXCLUDED.col for every
 * column listed in the INSERT column list (best-effort; falls back to
 * DO NOTHING when no column list is present).
 */
function rewriteInsertOr(
  sql: string,
  arbiterFor?: (table: string) => string[] | undefined
): string {
  const re = /\b(INSERT\s+OR\s+(?:IGNORE|REPLACE|ROLLBACK|ABORT|FAIL))\b|\bREPLACE\s+INTO\b/gi;
  let m: RegExpExecArray | null;
  const hits: Array<{
    start: number;
    end: number;
    kind: "ignore" | "replace";
    replacement: string;
  }> = [];
  while ((m = re.exec(sql)) !== null) {
    const token = m[0].toUpperCase();
    const kind = token.includes("IGNORE") ? "ignore" : "replace";
    // `REPLACE INTO` becomes `INSERT INTO`; `INSERT OR <mode>` becomes `INSERT`.
    const replacement = token === "REPLACE INTO" ? "INSERT INTO" : "INSERT";
    hits.push({ start: m.index, end: m.index + m[0].length, kind, replacement });
  }
  if (hits.length === 0) return sql;

  let out = sql;
  // Apply from the end so earlier indices stay valid.
  for (let k = hits.length - 1; k >= 0; k--) {
    const h = hits[k];
    out = out.slice(0, h.start) + h.replacement + out.slice(h.end);
    if (h.kind === "ignore") {
      out = appendOnConflict(out, "DO NOTHING");
    } else {
      // Re-derive the table name from the statement at/after this hit so the
      // arbiter lookup targets the right table (upsert may appear in the middle
      // of a multi-statement string). The token at h.start is already rewritten
      // to `INSERT INTO`; earlier hits may still be raw INSERT OR REPLACE, so
      // accept an optional OR <mode> between INSERT and INTO.
      const tail = out.slice(h.start);
      const tableM = /\bINSERT\s+(?:OR\s+[A-Z]+\s+)?INTO\s+([A-Za-z_][A-Za-z0-9_]*)/i.exec(tail);
      const arbiter = tableM ? arbiterFor?.(tableM[1]) : undefined;
      out = appendOnConflictUpsert(out, arbiter);
    }
  }
  return out;
}

/**
 * Append `ON CONFLICT DO NOTHING` before the statement terminator. If an
 * ON CONFLICT clause already exists, leave it alone.
 */
function appendOnConflict(sql: string, clause: string): string {
  if (/\bON\s+CONFLICT\b/i.test(sql)) return sql;
  const trimmed = sql.replace(/;+\s*$/, "");
  return `${trimmed} ON CONFLICT ${clause}`;
}

/**
 * Best-effort upsert: `INSERT INTO t (a, b, c) VALUES ... ON CONFLICT DO
 * UPDATE SET a=EXCLUDED.a, b=EXCLUDED.b, c=EXCLUDED.c`. When no column list
 * is present, falls back to ON CONFLICT DO NOTHING (safe, no data loss).
 */
function appendOnConflictUpsert(sql: string, arbiterCols?: string[]): string {
  if (/\bON\s+CONFLICT\b/i.test(sql)) return sql;
  const trimmed = sql.replace(/;+\s*$/, "");
  // Locate the column list: "INSERT INTO <name> ( ... )"
  const m = /^\s*INSERT\s+INTO\s+[A-Za-z_][A-Za-z0-9_]*\s*\(\s*([^)]*)\)/i.exec(trimmed);
  if (!m) return `${trimmed} ON CONFLICT DO NOTHING`;
  const cols = m[1]
    .split(",")
    .map((c) => c.trim().replace(/^"|"$/g, ""))
    .filter(Boolean);
  if (cols.length === 0) return `${trimmed} ON CONFLICT DO NOTHING`;
  // PG requires an arbiter (conflict target) for DO UPDATE. When the primary
  // key is known, target it and exclude PK columns from the assignment list;
  // otherwise fall back to DO NOTHING (safe, never a syntax error).
  if (arbiterCols && arbiterCols.length > 0) {
    const target = arbiterCols.map((c) => `"${c}"`).join(", ");
    const pkSet = new Set(arbiterCols.map((c) => c.toLowerCase()));
    const updatable = cols.filter((c) => !pkSet.has(c.toLowerCase()));
    const assignments =
      updatable.length > 0 ? updatable.map((c) => `${c} = EXCLUDED.${c}`).join(", ") : "1 = 1";
    return `${trimmed} ON CONFLICT (${target}) DO UPDATE SET ${assignments}`;
  }
  return `${trimmed} ON CONFLICT DO NOTHING`;
}

/** Rewrite AUTOINCREMENT and bare INTEGER PRIMARY KEY in DDL. */
function rewriteDdl(sql: string): string {
  let out = sql;
  // AUTOINCREMENT (after INTEGER PRIMARY KEY) → identity.
  out = out.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, "BIGSERIAL PRIMARY KEY");
  out = out.replace(/\bAUTOINCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY");
  // "INTEGER PRIMARY KEY" alone (no AUTOINCREMENT) → BIGSERIAL PRIMARY KEY.
  out = out.replace(/\bINTEGER\s+PRIMARY\s+KEY\b/gi, "BIGSERIAL PRIMARY KEY");
  // "INTEGER NOT NULL PRIMARY KEY" ordering.
  out = out.replace(/\bINTEGER\s+NOT\s+NULL\s+PRIMARY\s+KEY\b/gi, "BIGSERIAL PRIMARY KEY");
  return out;
}

/** Rewrite time functions to PG equivalents. */
function rewriteTimeFns(sql: string): string {
  let out = sql;
  // unixepoch('now') and unixepoch(<expr>)
  out = out.replace(/unixepoch\s*\(\s*'now'\s*\)/gi, "(EXTRACT(EPOCH FROM NOW()))");
  out = out.replace(/unixepoch\s*\(/gi, "(EXTRACT(EPOCH FROM ");
  // datetime('now') → NOW(); datetime(<expr>) → to_timestamp(<expr>)
  out = out.replace(/datetime\s*\(\s*'now'\s*\)/gi, "NOW()");
  out = out.replace(/datetime\s*\(\s*([^)]*?)\s*\)/gi, (match, inner: string) => {
    const arg = inner.trim();
    // Strip modifier arguments like 'utc' — unsupported, keep first arg.
    const first = arg.split(/,\s*/)[0];
    return `to_timestamp(${first})`;
  });
  // strftime('%s', <expr>) → EXTRACT(EPOCH FROM <expr>)
  out = out.replace(/strftime\s*\(\s*'%s'\s*,\s*([^)]*?)\s*\)/gi, "EXTRACT(EPOCH FROM $1)");
  // strftime('<fmt>', <expr>) → to_char(<expr> AT TIME ZONE 'UTC', '<pg fmt>')
  // <expr> may be a TEXT column (ISO-8601 strings in SQLite); PG's
  // AT TIME ZONE needs a timestamptz, so cast explicitly. ISO strings are
  // parsed fine; real timestamptz columns pass through the cast harmlessly.
  out = out.replace(
    /strftime\s*\(\s*'([^']*)'\s*,\s*([^)]*?)\s*\)/gi,
    (match: string, fmt: string, expr: string) =>
      `to_char((${expr.trim()})::timestamptz AT TIME ZONE 'UTC', '${sqliteStrftimeToPg(fmt)}')`
  );
  return out;
}

/** Map a SQLite strftime format string to a PostgreSQL to_char pattern. */
export function sqliteStrftimeToPg(fmt: string): string {
  const map: Record<string, string> = {
    "%Y": "YYYY",
    "%m": "MM",
    "%d": "DD",
    "%H": "HH24",
    "%M": "MI",
    "%S": "SS",
    "%f": "MS",
    "%j": "DDD",
    "%w": "D",
    "%W": "WW",
    "%s": '""', // epoch handled separately — placeholder, never emitted
  };
  let out = "";
  for (let i = 0; i < fmt.length; i++) {
    if (fmt[i] === "%" && i + 1 < fmt.length) {
      const key = `%${fmt[i + 1]}`;
      if (map[key]) {
        out += map[key];
        i++;
        continue;
      }
    }
    // Literal chars: letters would be parsed as pattern tokens — quote them.
    out += /[A-Za-z]/.test(fmt[i]) ? `"${fmt[i]}"` : fmt[i];
  }
  return out;
}

/**
 * Main entry: translate a SQLite SQL statement to PostgreSQL.
 * Placeholder rewriting happens first so `$n` markers from rewritten
 * function calls are not re-scanned.
 */
export function translateSqliteToPostgres(
  sql: string,
  arbiterFor?: (table: string) => string[] | undefined
): string {
  let out = sql;
  out = rewriteInsertOr(out, arbiterFor);
  out = rewriteDdl(out);
  out = rewriteTimeFns(out);
  // COLLATE NOCASE → LOWER(<expr>). PostgreSQL has no NOCASE collation;
  // lowering the expression reproduces case-insensitive ordering/comparison.
  out = out.replace(/([A-Za-z_][A-Za-z0-9_.]*|"[^"]+")\s+COLLATE\s+NOCASE\b/gi, "LOWER($1)");
  // SQLite accepts double-quoted string literals in DEFAULT (e.g. DEFAULT
  // "upstream"); PostgreSQL treats them as identifiers. Rewrite to single quotes.
  out = out.replace(/\bDEFAULT\s*"([^"]+)"/gi, "DEFAULT '$1'");
  // randomblob(n) → gen_random_uuid() (PG core builtin; gen_random_bytes is
  // unavailable in some distributions). hex(randomblob(n)) → hex string.
  out = out.replace(
    /hex\s*\(\s*randomblob\s*\([^)]*\)\s*\)/gi,
    "replace(gen_random_uuid()::text, '-', '')"
  );
  out = out.replace(/randomblob\s*\(/gi, "gen_random_uuid()::text /* randomblob */");
  out = rewritePlaceholders(out);
  return out;
}

/**
 * Translate a PRAGMA query to an information_schema query.
 * Supported: PRAGMA table_info(<name>) — returns rows with the same shape
 * the SQLite pragma returns (cid, name, type, notnull, dflt_value, pk).
 */
export function pragmaToQuery(pragmaStr: string): { sql: string; params: unknown[] } | null {
  const m = /PRAGMA\s+table_info\s*\(\s*([^)]+)\s*\)/i.exec(pragmaStr.trim());
  if (!m) return null;
  const table = m[1].trim().replace(/^['"]|['"]$/g, "");
  return {
    sql: `
      SELECT
        ordinal_position - 1 AS cid,
        column_name AS name,
        CASE WHEN data_type IS NULL THEN '' ELSE data_type END AS type,
        CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
        COALESCE(column_default, '') AS dflt_value,
        CASE WHEN ordinal_position IN (
          SELECT kcu.ordinal_position
          FROM information_schema.table_constraints tc
          JOIN information_schema.key_column_usage kcu
            ON tc.constraint_name = kcu.constraint_name
           AND tc.table_schema = kcu.table_schema
          WHERE tc.table_name = $1
            AND tc.constraint_type = 'PRIMARY KEY'
        ) THEN 1 ELSE 0 END AS pk
      FROM information_schema.columns
      WHERE table_name = $1
      ORDER BY ordinal_position
    `,
    params: [table],
  };
}

/**
 * Translate a query against sqlite_master / sqlite_schema to a
 * information_schema query. Returns null when the query is not recognised.
 */
export function sqliteMasterToQuery(sql: string): { sql: string; params: unknown[] } | null {
  const m = /FROM\s+(?:sqlite_master|sqlite_schema)\b/i.exec(sql);
  if (!m) return null;
  const tail = sql.slice(m.index + m[0].length);
  const where = /\s+WHERE\s+(.*)$/is.exec(tail)?.[1] ?? "";
  // Typical patterns: WHERE type = 'table' / WHERE name = ? / WHERE tbl_name = ?
  let cond = "";
  const params: unknown[] = [];
  const typeM = /type\s*=\s*'([^']+)'/i.exec(where);
  if (typeM) cond += ` AND table_type = '${typeM[1].toUpperCase()}'`;
  const nameM = /(?:name|tbl_name)\s*=\s*(\?|\$?\d+)/i.exec(where);
  if (nameM) {
    cond += ` AND table_name = $1`;
    if (nameM[1].startsWith("$")) params.push(Number(nameM[1].slice(1)));
    else if (nameM[1] === "?") params.push(null); // filled by adapter param mapping
  }
  return {
    sql: `
      SELECT
        CASE WHEN table_type = 'VIEW' THEN 'view' ELSE 'table' END AS type,
        table_name AS name,
        table_name AS tbl_name,
        NULL AS rootpage,
        '' AS sql
      FROM information_schema.tables
      WHERE table_schema = 'public'${cond}
    `,
    params,
  };
}
