/**
 * postgresDialect.ts — SQLite → PostgreSQL dialect translation.
 *
 * Phase 2.8 (pg-3): business modules write SQLite-flavoured SQL; the
 * PostgresAdapter runs every statement through `translateSqliteToPostgres`
 * so modules stay driver-agnostic. Translation is conservative: only known
 * SQLite-only constructs are rewritten, everything else passes through and
 * PostgreSQL itself reports anything it cannot parse.
 *
 * Rewrites (in priority order):
 *   1. `?` placeholders → `$1..$n` (outside string literals / comments)
 *   2. `INSERT OR IGNORE` → `INSERT ... ON CONFLICT DO NOTHING`
 *   3. `INSERT OR REPLACE` / `REPLACE INTO` → `INSERT ... ON CONFLICT DO UPDATE`
 *      (upsert of every column from the VALUES / the conflict target is left
 *      to the caller when a unique key is not inferable)
 *   4. `AUTOINCREMENT` → `GENERATED BY DEFAULT AS IDENTITY`
 *   5. `unixepoch('now')` → `(EXTRACT(EPOCH FROM NOW()))`
 *   6. `datetime('now')` → `NOW()`; `datetime(<expr>)` → `to_timestamp(<expr>)`
 *   7. `strftime('%s', <expr>)` → `EXTRACT(EPOCH FROM <expr>)`
 *   8. `INTEGER PRIMARY KEY` (bare) → `BIGSERIAL PRIMARY KEY`
 *
 * NOT rewritten here (handled by the adapter layer):
 *   - `PRAGMA table_info(x)` / `sqlite_master` — translated to
 *     information_schema queries by the adapter with result-shape mapping.
 */

/** Scan state while rewriting SQL. */
interface Cursor {
  sql: string;
  i: number;
  out: string[];
  paramIndex: number;
  /** Set when we are inside a single/double-quoted string or backticks. */
  quote: "'" | '"' | "`" | null;
}

function isIdentifierChar(ch: string): boolean {
  return /[A-Za-z0-9_$]/.test(ch);
}

/**
 * Rewrite `?` placeholders to `$n`, skipping string literals ('...', "...",
 * `...`) and line/block comments. Returns the rewritten SQL.
 */
function rewritePlaceholders(sql: string): string {
  let quote: "'" | '"' | "`" | null = null;
  let lineComment = false;
  let blockComment = false;
  let n = 0;
  let out = "";

  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    const next = sql[i + 1];

    if (lineComment) {
      out += ch;
      if (ch === "\n") lineComment = false;
      continue;
    }
    if (blockComment) {
      out += ch;
      if (ch === "*" && next === "/") {
        out += "/";
        i++;
        blockComment = false;
      }
      continue;
    }
    if (quote) {
      out += ch;
      if (ch === quote) {
        // Handle doubled quotes inside the literal ('' / "" escapes).
        if (next === quote) {
          out += next;
          i++;
        } else {
          quote = null;
        }
      }
      continue;
    }
    if (ch === "-" && next === "-") {
      lineComment = true;
      out += "--";
      i++;
      continue;
    }
    if (ch === "/" && next === "*") {
      blockComment = true;
      out += "/*";
      i++;
      continue;
    }
    if (ch === "'" || ch === '"' || ch === "`") {
      quote = ch;
      out += ch;
      continue;
    }
    if (ch === "?") {
      n++;
      out += `$${n}`;
      continue;
    }
    out += ch;
  }
  return out;
}

/** Case-insensitive keyword match at cursor position (word boundary). */
function kwAt(sql: string, i: number, kw: string): boolean {
  if (sql.length - i < kw.length) return false;
  if (
    !sql
      .slice(i, i + kw.length)
      .toUpperCase()
      .startsWith(kw)
  )
    return false;
  const before = sql[i - 1];
  const after = sql[i + kw.length];
  const okBefore = before === undefined || !isIdentifierChar(before);
  const okAfter = after === undefined || !isIdentifierChar(after);
  return okBefore && okAfter;
}

/**
 * Rewrite INSERT OR IGNORE / INSERT OR REPLACE / REPLACE INTO to PG upserts.
 * INSERT OR IGNORE → ON CONFLICT DO NOTHING (append at end of statement).
 * INSERT OR REPLACE → ON CONFLICT DO UPDATE SET col=EXCLUDED.col for every
 * column listed in the INSERT column list (best-effort; falls back to
 * DO NOTHING when no column list is present).
 */
function rewriteInsertOr(
  sql: string,
  arbiterFor?: (table: string) => string[] | undefined
): string {
  const re = /\b(INSERT\s+OR\s+(?:IGNORE|REPLACE|ROLLBACK|ABORT|FAIL))\b|\bREPLACE\s+INTO\b/gi;
  let m: RegExpExecArray | null;
  const hits: Array<{
    start: number;
    end: number;
    kind: "ignore" | "replace";
    replacement: string;
  }> = [];
  while ((m = re.exec(sql)) !== null) {
    const token = m[0].toUpperCase();
    const kind = token.includes("IGNORE") ? "ignore" : "replace";
    // `REPLACE INTO` becomes `INSERT INTO`; `INSERT OR <mode>` becomes `INSERT`.
    const replacement = token === "REPLACE INTO" ? "INSERT INTO" : "INSERT";
    hits.push({ start: m.index, end: m.index + m[0].length, kind, replacement });
  }
  if (hits.length === 0) return sql;

  let out = sql;
  // Apply from the end so earlier indices stay valid.
  for (let k = hits.length - 1; k >= 0; k--) {
    const h = hits[k];
    out = out.slice(0, h.start) + h.replacement + out.slice(h.end);
    if (h.kind === "ignore") {
      out = appendOnConflict(out, "DO NOTHING");
    } else {
      // Re-derive the table name from the statement at/after this hit so the
      // arbiter lookup targets the right table (upsert may appear in the middle
      // of a multi-statement string). The token at h.start is already rewritten
      // to `INSERT INTO`; earlier hits may still be raw INSERT OR REPLACE, so
      // accept an optional OR <mode> between INSERT and INTO.
      const tail = out.slice(h.start);
      const tableM = /\bINSERT\s+(?:OR\s+[A-Z]+\s+)?INTO\s+([A-Za-z_][A-Za-z0-9_]*)/i.exec(tail);
      const arbiter = tableM ? arbiterFor?.(tableM[1]) : undefined;
      out = appendOnConflictUpsert(out, arbiter);
    }
  }
  return out;
}

/**
 * Append `ON CONFLICT DO NOTHING` before the statement terminator. If an
 * ON CONFLICT clause already exists, leave it alone.
 */
function appendOnConflict(sql: string, clause: string): string {
  if (/\bON\s+CONFLICT\b/i.test(sql)) return sql;
  const trimmed = sql.replace(/;+\s*$/, "");
  return `${trimmed} ON CONFLICT ${clause}`;
}

/**
 * Best-effort upsert: `INSERT INTO t (a, b, c) VALUES ... ON CONFLICT DO
 * UPDATE SET a=EXCLUDED.a, b=EXCLUDED.b, c=EXCLUDED.c`. When no column list
 * is present, falls back to ON CONFLICT DO NOTHING (safe, no data loss).
 */
function appendOnConflictUpsert(sql: string, arbiterCols?: string[]): string {
  if (/\bON\s+CONFLICT\b/i.test(sql)) return sql;
  const trimmed = sql.replace(/;+\s*$/, "");
  // Locate the column list: "INSERT INTO <name> ( ... )"
  const m = /^\s*INSERT\s+INTO\s+[A-Za-z_][A-Za-z0-9_]*\s*\(\s*([^)]*)\)/i.exec(trimmed);
  if (!m) return `${trimmed} ON CONFLICT DO NOTHING`;
  const cols = m[1]
    .split(",")
    .map((c) => c.trim().replace(/^"|"$/g, ""))
    .filter(Boolean);
  if (cols.length === 0) return `${trimmed} ON CONFLICT DO NOTHING`;
  // PG requires an arbiter (conflict target) for DO UPDATE. When the primary
  // key is known, target it and exclude PK columns from the assignment list;
  // otherwise fall back to DO NOTHING (safe, never a syntax error).
  if (arbiterCols && arbiterCols.length > 0) {
    const target = arbiterCols.map((c) => `"${c}"`).join(", ");
    const pkSet = new Set(arbiterCols.map((c) => c.toLowerCase()));
    const updatable = cols.filter((c) => !pkSet.has(c.toLowerCase()));
    const assignments =
      updatable.length > 0 ? updatable.map((c) => `${c} = EXCLUDED.${c}`).join(", ") : "1 = 1";
    return `${trimmed} ON CONFLICT (${target}) DO UPDATE SET ${assignments}`;
  }
  return `${trimmed} ON CONFLICT DO NOTHING`;
}

/**
 * Rewrite assignments in an existing `ON CONFLICT ... DO UPDATE SET` clause so
 * bare column references on the RIGHT side are qualified with the target table
 * name. PostgreSQL reports `column reference "x" is ambiguous` for the
 * sliding-window counter pattern `consumed = consumed + EXCLUDED.consumed` —
 * the bare `consumed` on the RHS is ambiguous between the target-table column
 * and the excluded row. SQLite accepts it; PG requires the RHS to be
 * qualified: `consumed = quota_consumption.consumed + EXCLUDED.consumed`.
 * (The assignment LHS must stay bare — `SET table.col = ...` is itself a PG
 * syntax error.)
 *
 * Only statements that ALREADY carry `ON CONFLICT` are touched (hand-written
 * upserts like quotaConsumption.ts). Statements rewritten by
 * appendOnConflictUpsert emit `col = EXCLUDED.col` where the RHS is fully
 * qualified, so they are safe — but they pass through here unchanged anyway.
 */
function rewriteConflictAssignments(sql: string): string {
  if (!/\bON\s+CONFLICT\b/i.test(sql)) return sql;
  const tableM = /^\s*INSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)/i.exec(sql);
  if (!tableM) return sql;
  const table = tableM[1];

  // Only touch `DO UPDATE SET` sections.
  return sql.replace(
    /\bDO\s+UPDATE\s+SET\s+([\s\S]*?)(?=\b(?:WHERE|RETURNING)\b|;|$)/i,
    (_m: string, body: string) => {
      // Split into assignment items on top-level commas, then qualify bare
      // identifiers only on the RHS (after the first `=`).
      const items = body.split(",");
      const rewrittenItems = items.map((item) => {
        const eqIdx = item.indexOf("=");
        if (eqIdx === -1) return item; // no assignment — leave alone
        const lhs = item.slice(0, eqIdx + 1);
        const rhs = item.slice(eqIdx + 1);
        const qualifiedRhs = rhs.replace(
          /(?<![A-Za-z0-9_."])([a-z_][a-z0-9_]*)(?![A-Za-z0-9_."])/g,
          (ident: string) => {
            if (ident.toLowerCase() === "excluded") return ident;
            return `${table}.${ident}`;
          }
        );
        return lhs + qualifiedRhs;
      });
      return `DO UPDATE SET ${rewrittenItems.join(",")}`;
    }
  );
}

/** Rewrite AUTOINCREMENT and bare INTEGER PRIMARY KEY in DDL. */
function rewriteDdl(sql: string): string {
  let out = sql;
  // AUTOINCREMENT (after INTEGER PRIMARY KEY) → identity.
  out = out.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, "BIGSERIAL PRIMARY KEY");
  out = out.replace(/\bAUTOINCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY");
  // "INTEGER PRIMARY KEY" alone (no AUTOINCREMENT) → BIGSERIAL PRIMARY KEY.
  out = out.replace(/\bINTEGER\s+PRIMARY\s+KEY\b/gi, "BIGSERIAL PRIMARY KEY");
  // "INTEGER NOT NULL PRIMARY KEY" ordering.
  out = out.replace(/\bINTEGER\s+NOT\s+NULL\s+PRIMARY\s+KEY\b/gi, "BIGSERIAL PRIMARY KEY");
  return out;
}

/**
 * Find the range of a function call with balanced parentheses, given the
 * position of the opening paren. Returns { inner, end } where `inner` is the
 * substring between the parens and `end` is the index just past the closing
 * paren. Skips string literals so parens inside strings are not mistaken for
 * the terminator. Returns null when unbalanced / EOF.
 */
function findBalancedParen(sql: string, open: number): { inner: string; end: number } | null {
  let depth = 0;
  let quote: "'" | '"' | "`" | null = null;
  for (let i = open; i < sql.length; i++) {
    const ch = sql[i];
    if (quote) {
      if (ch === quote) {
        if (sql[i + 1] === quote) {
          i++; // doubled quote escape
        } else {
          quote = null;
        }
      }
      continue;
    }
    if (ch === "'" || ch === '"' || ch === "`") {
      quote = ch;
      continue;
    }
    if (ch === "(") {
      depth++;
      continue;
    }
    if (ch === ")") {
      depth--;
      if (depth === 0) {
        return { inner: sql.slice(open + 1, i), end: i + 1 };
      }
    }
  }
  return null;
}

/** Split comma-separated args, respecting nested parens and string literals. */
function splitTopLevelArgs(s: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let quote: "'" | '"' | "`" | null = null;
  let cur = "";
  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    if (quote) {
      cur += ch;
      if (ch === quote) {
        if (s[i + 1] === quote) {
          cur += s[++i];
        } else {
          quote = null;
        }
      }
      continue;
    }
    if (ch === "'" || ch === '"' || ch === "`") {
      quote = ch;
      cur += ch;
      continue;
    }
    if (ch === "(") {
      depth++;
      cur += ch;
      continue;
    }
    if (ch === ")") {
      depth--;
      cur += ch;
      continue;
    }
    if (ch === "," && depth === 0) {
      out.push(cur);
      cur = "";
      continue;
    }
    cur += ch;
  }
  out.push(cur);
  return out;
}

/** Convert SQLite time modifiers ('-1 hour', '+30 minutes', 'unixepoch', ...) to a PG INTERVAL suffix. */
function intervalModifier(mods: string): string {
  const singular: Array<[string, string]> = [
    ["millisecond", "milliseconds"],
    ["second", "seconds"],
    ["minute", "minutes"],
    ["hour", "hours"],
    ["day", "days"],
    ["week", "weeks"],
    ["month", "months"],
    ["year", "years"],
  ];
  for (const m of mods.split(",")) {
    const t = m.trim().replace(/['"]/g, "");
    const match = /^([+-]?\d+)\s+([a-zA-Z]+)$/.exec(t);
    if (match) {
      const unit = match[2].toLowerCase();
      const sig = singular.find(([s]) => unit === s || unit === s + "s");
      if (sig) {
        const sign = match[1].startsWith("-") ? "-" : "+";
        const amount = match[1].replace(/^[+-]/, "");
        return `${sign} INTERVAL '${amount} ${sig[1]}'`;
      }
    }
  }
  return "+ INTERVAL '1 hour'";
}

/** Rewrite a single `datetime(...)` call to its PG equivalent. */
function rewriteDatetimeCall(inner: string): string {
  const args = splitTopLevelArgs(inner);
  const first = (args[0] ?? "").trim();
  if (/^['"]?now['"]?$/i.test(first)) {
    if (args.length > 1) {
      return `NOW() ${intervalModifier(args.slice(1).join(", "))}`;
    }
    return "NOW()";
  }
  // datetime(<expr>) / datetime(<expr>, 'unixepoch') → to_timestamp(<first>).
  // Recursively rewrite time fns nested inside the argument.
  return `to_timestamp(${rewriteTimeFns(first)})`;
}

/**
 * Cast an arbitrary SQL expression to a timestamptz so EXTRACT / to_char
 * receive a timestamp. Text ISO strings parse fine; real timestamptz columns
 * pass through the identity cast harmlessly.
 */
function argToTimestamptz(expr: string): string {
  const t = expr.trim();
  if (!t) return t;
  return `(${t})::timestamptz`;
}

/** Rewrite time functions (datetime / strftime / unixepoch) using balanced-paren matching. */
function rewriteTimeFns(sql: string): string {
  let out = "";
  let i = 0;
  while (i < sql.length) {
    const rest = sql.slice(i);
    // unixepoch('now') / unixepoch(<expr>)
    const ue = /^unixepoch\s*\(/i.exec(rest);
    if (ue) {
      const open = i + ue[0].length - 1;
      const b = findBalancedParen(sql, open);
      if (b) {
        const inner = b.inner.trim();
        out +=
          inner.toLowerCase() === "'now'"
            ? "(EXTRACT(EPOCH FROM NOW()))"
            : `(EXTRACT(EPOCH FROM ${argToTimestamptz(rewriteTimeFns(inner))}))`;
        i = b.end;
        continue;
      }
    }
    // strftime('<fmt>', <expr>)
    const sf = /^strftime\s*\(/i.exec(rest);
    if (sf) {
      const open = i + sf[0].length - 1;
      const b = findBalancedParen(sql, open);
      if (b) {
        const parts = splitTopLevelArgs(b.inner);
        const fmt = (parts[0] ?? "").trim().replace(/^'|'$/g, "");
        const expr = rewriteTimeFns((parts[1] ?? "").trim());
        if (fmt === "%s") {
          out += `(EXTRACT(EPOCH FROM ${argToTimestamptz(expr)}))`;
        } else if (fmt !== "") {
          out += `to_char(${argToTimestamptz(expr)} AT TIME ZONE 'UTC', '${sqliteStrftimeToPg(fmt)}')`;
        } else {
          out += sql.slice(i, b.end);
        }
        i = b.end;
        continue;
      }
    }
    // datetime(...)
    const dt = /^datetime\s*\(/i.exec(rest);
    if (dt) {
      const open = i + dt[0].length - 1;
      const b = findBalancedParen(sql, open);
      if (b) {
        out += rewriteDatetimeCall(b.inner);
        i = b.end;
        continue;
      }
    }
    out += sql[i];
    i++;
  }
  return out;
}

/** Map a SQLite strftime format string to a PostgreSQL to_char pattern. */
export function sqliteStrftimeToPg(fmt: string): string {
  const map: Record<string, string> = {
    "%Y": "YYYY",
    "%m": "MM",
    "%d": "DD",
    "%H": "HH24",
    "%M": "MI",
    "%S": "SS",
    "%f": "MS",
    "%j": "DDD",
    "%w": "D",
    "%W": "WW",
    "%s": '""', // epoch handled separately — placeholder, never emitted
  };
  let out = "";
  for (let i = 0; i < fmt.length; i++) {
    if (fmt[i] === "%" && i + 1 < fmt.length) {
      const key = `%${fmt[i + 1]}`;
      if (map[key]) {
        out += map[key];
        i++;
        continue;
      }
    }
    // Literal chars: letters would be parsed as pattern tokens — quote them.
    out += /[A-Za-z]/.test(fmt[i]) ? `"${fmt[i]}"` : fmt[i];
  }
  return out;
}

/**
 * Main entry: translate a SQLite SQL statement to PostgreSQL.
 * Placeholder rewriting happens first so `$n` markers from rewritten
 * function calls are not re-scanned.
 */
export function translateSqliteToPostgres(
  sql: string,
  arbiterFor?: (table: string) => string[] | undefined
): string {
  let out = sql;
  out = rewriteInsertOr(out, arbiterFor);
  out = rewriteConflictAssignments(out);
  out = rewriteDdl(out);
  out = rewriteTimeFns(out);
  // PostgreSQL folds unquoted identifiers to lower case, so `as remainingPct`
  // comes back as `remainingpct` and every JS reader that expects the camelCase
  // alias reads undefined → 0. Quote camelCase aliases (and their GROUP BY /
  // ORDER BY references) so PG preserves the case exactly as SQLite did.
  // Lower-case aliases are unaffected (folding is a no-op for them), and
  // expressions / function calls (uppercase or parenthesised) are left alone.
  out = quoteCamelAliases(out);
  // NOTE: no blanket camelCase quoting here. Bare camelCase identifiers also
  // appear as SQLite named-parameter suffixes (@lastUsedAt) and as column
  // references in SET/WHERE/JOIN clauses whose physical columns are
  // snake_case (auth_type, is_active, last_used_at). Quoting those breaks
  // binding and column resolution ("column \"authType\" does not exist").
  // Alias references that genuinely need quoting are handled inside
  // quoteSelectList / quoteGroupItems (SELECT/GROUP BY/ORDER BY items only).
  // COLLATE NOCASE → LOWER(<expr>). PostgreSQL has no NOCASE collation;
  // lowering the expression reproduces case-insensitive ordering/comparison.
  // Handles bare identifiers, quoted identifiers, and `?` placeholders (the
  // combos route queries use `name = ? COLLATE NOCASE`).
  out = out.replace(
    /((?:[A-Za-z_][A-Za-z0-9_.]*)|(?:"[^"]+")|\?)\s+COLLATE\s+NOCASE\b/gi,
    "LOWER($1)"
  );
  // SQLite accepts double-quoted string literals in DEFAULT (e.g. DEFAULT
  // "upstream"); PostgreSQL treats them as identifiers. Rewrite to single quotes.
  out = out.replace(/\bDEFAULT\s*"([^"]+)"/gi, "DEFAULT '$1'");
  // randomblob(n) → gen_random_uuid() (PG core builtin; gen_random_bytes is
  // unavailable in some distributions). hex(randomblob(n)) → hex string.
  out = out.replace(
    /hex\s*\(\s*randomblob\s*\([^)]*\)\s*\)/gi,
    "replace(gen_random_uuid()::text, '-', '')"
  );
  out = out.replace(/randomblob\s*\(/gi, "gen_random_uuid()::text /* randomblob */");
  // SQLite NULL-safe `IS ?` / `IS NOT ?` comparisons are rejected by PG
  // (`x IS $2` is a syntax error — PG only accepts IS NULL/TRUE/FALSE/UNKNOWN).
  out = rewriteIsParam(out);
  out = rewritePlaceholders(out);
  return out;
}

/**
 * Quote camelCase SQL aliases so PostgreSQL preserves their case.
 *
 * PostgreSQL folds unquoted identifiers to lower case, so `AS remainingPct`
 * in a SELECT comes back as `remainingpct` and every JS reader expecting the
 * camelCase alias reads undefined → 0 / null. SQLite returned the alias with
 * its original case, so the fix is to make PG do the same by quoting it.
 *
 * Handles two shapes:
 *   1. `AS <camelCase>` — the alias definition itself.
 *   2. `<camelCase>` in GROUP BY / ORDER BY clauses — bare identifiers that
 *      reference the quoted aliases. If only the SELECT alias were quoted, the
 *      unquoted GROUP BY reference would fold to lower case and no longer
 *      match the quoted alias → PG error. So both sides get quoted together.
 *
 * Only identifiers that START lower-case and CONTAIN an upper-case letter are
 * touched: fully-lower-case aliases (e.g. `date`, `requests`) fold to
 * themselves and need no quoting, and fully-upper-case tokens are function
 * names (e.g. `LOWER(...)`) or keywords that must not be touched. Expressions
 * (parenthesised, e.g. `substr(timestamp, 1, 10)`) are skipped because the
 * identifier regex requires a word boundary after the identifier.
 */
function quoteCamelAliases(sql: string): string {
  // 1. AS aliases: `AS serviceTier` → `AS "serviceTier"`.
  //    Case-insensitive keyword (as/AS), but the identifier itself must be
  //    strict camelCase (starts lower, contains upper) — a case-insensitive
  //    character class would also match all-lower aliases and then GROUP BY
  //    (which only quotes camelCase) would disagree with the SELECT list.
  //    NOTE: performed last via quoteClauseRefs is intentionally avoided —
  //    AS aliases live both inside and outside subqueries and are uniform, so
  //    a plain global replace is correct here.
  let out = sql.replace(/\b[Aa][Ss]\s+([a-z][A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)\b/g, 'AS "$1"');
  // 2+3. SELECT-list / GROUP BY / ORDER BY references, processed per top-level
  //    clause so nested subqueries are handled independently (a GROUP BY inside
  //    a subquery must not swallow an outer GROUP BY; a SELECT-list bare
  //    camelCase identifier referencing a subquery alias must be quoted).
  //    A single scan tracks paren depth and splits on top-level clause
  //    keywords and on the top-level `)` that closes a subquery.
  out = quoteClauseRefs(out);
  return out;
}

/**
 * Rewrite bare camelCase identifiers inside SELECT / GROUP BY / ORDER BY
 * clauses, per top-level (depth-0) clause, so nested subqueries are treated
 * independently.
 *
 * It scans the SQL tracking paren depth (and single/double-quoted string
 * literals) and recognises the depth-0 keyword positions for SELECT,
 * GROUP BY and ORDER BY. Each clause's body runs until the next depth-0
 * clause keyword, a depth-0 `)` (subquery close), or EOF:
 *
 *   - SELECT body  → quoteSelectList  (quote bare camelCase item references)
 *   - GROUP BY/ORDER BY body → quoteGroupItems (quote items, incl. ASC/DESC)
 *
 * The clause keyword itself and any `)`/other clause boundaries are re-emitted
 * verbatim. Function-call parens (e.g. `strftime(...)`, `to_char(...)`) keep
 * depth > 0 and therefore never terminate a clause or get treated as items.
 */
function quoteClauseRefs(sql: string): string {
  // Depth-0 clause keywords that BOUND a SELECT/GROUP BY/ORDER BY body. Any of
  // these terminates the current clause body during the scan. Only SELECT,
  // GROUP BY and ORDER BY bodies are rewritten; the rest act purely as
  // separators and are re-emitted verbatim.
  const KW: string[] = [
    "SELECT",
    "FROM",
    "JOIN",
    "WHERE",
    "GROUP BY",
    "ORDER BY",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "UNION",
  ];

  // Match a depth-0 keyword at pos (case-insensitive, word-boundary).
  const matchKw = (pos: number, depth0: boolean): string | null => {
    if (!depth0) return null;
    const rest = sql;
    for (const kw of KW) {
      if (rest.slice(pos, pos + kw.length).toUpperCase() === kw) {
        const after = rest[pos + kw.length];
        if (after === undefined || /[\s(]/.test(after) || /[",)]/.test(after)) {
          return kw;
        }
      }
    }
    return null;
  };

  const PROCESS = new Set(["SELECT", "GROUP BY", "ORDER BY"]);
  const out: string[] = [];
  let i = 0;
  const n = sql.length;
  let depth = 0;
  let inSQuote = false;
  let inDQuote = false;
  let raw = "";

  const flushRaw = () => {
    if (raw) {
      out.push(raw);
      raw = "";
    }
  };

  while (i < n) {
    const ch = sql[i];

    // String literals.
    if (ch === "'") {
      raw += ch;
      if (!inDQuote) inSQuote = !inSQuote;
      i++;
      continue;
    }
    if (ch === '"') {
      raw += ch;
      if (!inSQuote) inDQuote = !inDQuote;
      i++;
      continue;
    }
    if (inSQuote || inDQuote) {
      raw += ch;
      i++;
      continue;
    }

    // Paren depth.
    if (ch === "(") {
      depth++;
      raw += ch;
      i++;
      continue;
    }
    if (ch === ")") {
      if (depth > 0) depth--;
      raw += ch;
      i++;
      continue;
    }

    // Clause keyword at ANY depth (CTEs and subqueries use parentheses, so a
    // `SELECT` inside WITH ... AS (...) is at depth>0 and must still be
    // rewritten). Bodies run to the matching close paren / next keyword.
    const kw = matchKw(i, true);
    if (kw) {
      flushRaw();
      out.push(kw);
      let body = "";
      let j = i + kw.length;
      let bdepth = 0;
      let bsQuote = false;
      let bdQuote = false;
      while (j < n) {
        const c = sql[j];
        if (c === "'") {
          if (!bdQuote) bsQuote = !bsQuote;
          body += c;
          j++;
          continue;
        }
        if (c === '"') {
          if (!bsQuote) bdQuote = !bdQuote;
          body += c;
          j++;
          continue;
        }
        if (bsQuote || bdQuote) {
          body += c;
          j++;
          continue;
        }
        if (c === "(") {
          bdepth++;
          body += c;
          j++;
          continue;
        }
        if (c === ")") {
          if (bdepth > 0) {
            bdepth--;
            body += c;
            j++;
            continue;
          }
          // depth-0 `)` closes a subquery → end clause body.
          break;
        }
        if (bdepth === 0 && matchKw(j, true)) break;
        body += c;
        j++;
      }
      if (PROCESS.has(kw)) {
        const processed = quoteFuncArgs(body);
        out.push(kw === "SELECT" ? quoteSelectList(processed) : quoteGroupItems(processed));
      } else {
        out.push(body);
      }
      i = j;
      continue;
    }

    raw += ch;
    i++;
  }
  flushRaw();
  return out.join("");
}

/**
 * Apply the correct item-quoter to a clause body based on its keyword.
 */
function processClauseBody(kw: string, body: string): string {
  if (kw === "SELECT") return quoteSelectList(body);
  return quoteGroupItems(body);
}

/**
 * Quote bare camelCase identifiers used as ARGUMENTS inside function calls,
 * e.g. `SUM(totalTokens)` → `SUM("totalTokens")`. Handles nested calls
 * (`COALESCE(SUM(totalTokens), 0)`) and quoted/string-literal arguments by
 * scanning with bracket tracking. Function NAMES (upper-case like SUM/GROUP)
 * and lower-case args (tokens_input, provider) are left untouched; already
 * quoted identifiers (`"totalTokens"`) are skipped so we never double-quote.
 */
function quoteFuncArgs(body: string): string {
  const out: string[] = [];
  let i = 0;
  const n = body.length;
  while (i < n) {
    const ch = body[i];
    // Skip string literals verbatim.
    if (ch === "'" || ch === '"') {
      const q = ch;
      let j = i + 1;
      while (j < n && body[j] !== q) {
        if (body[j] === "\\") j++;
        j++;
      }
      out.push(body.slice(i, Math.min(j + 1, n)));
      i = Math.min(j + 1, n);
      continue;
    }
    // Identify function-name followed by `(`.
    const fnMatch = /^[A-Za-z_][A-Za-z0-9_]*\s*\(/.exec(body.slice(i));
    if (fnMatch) {
      // The function name token:
      const nameTok = fnMatch[0].slice(0, fnMatch[0].indexOf("(")).trim();
      const openIdx = body.indexOf("(", i + nameTok.length);
      // Find matching close paren (handling nesting + string literals).
      let depth = 1;
      let j = openIdx + 1;
      while (j < n && depth > 0) {
        const c = body[j];
        if (c === "'" || c === '"') {
          const q = c;
          j++;
          while (j < n && body[j] !== q) {
            if (body[j] === "\\") j++;
            j++;
          }
          j = Math.min(j + 1, n);
          continue;
        }
        if (c === "(") depth++;
        else if (c === ")") depth--;
        if (depth > 0) j++;
      }
      const args = body.slice(openIdx + 1, j);
      const closeIdx = j;
      // Quote bare camelCase args inside (recursively for nested calls).
      // Only touch args that are a standalone strict-camelCase identifier
      // (not inside quotes, not preceded/followed by ident chars).
      const quotedArgs = args.replace(
        /(?<![A-Za-z0-9_"])([a-z][A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)(?![A-Za-z0-9_"])/g,
        '"$1"'
      );
      out.push(nameTok + "(" + quotedArgs + ")");
      i = Math.min(closeIdx + 1, n);
      continue;
    }
    // Plain text — advance one char.
    out.push(ch);
    i++;
  }
  return out.join("");
}

/**
 * Quote bare camelCase identifiers in a GROUP BY / ORDER BY item list.
 * Splits on top-level commas (parens tracked so `LOWER(p)` stays one item),
 * then quotes exactly those items that are a single strict-camelCase
 * identifier, optionally followed by ASC/DESC. Everything else (function
 * calls, lower-case aliases, qualified names) is preserved verbatim.
 */
function quoteGroupItems(rest: string): string {
  const parts: string[] = [];
  let depth = 0;
  let cur = "";
  for (const ch of rest) {
    if (ch === "(") depth++;
    else if (ch === ")") depth = Math.max(0, depth - 1);
    if (ch === "," && depth === 0) {
      parts.push(cur);
      cur = "";
    } else {
      cur += ch;
    }
  }
  parts.push(cur);
  return parts
    .map((item) =>
      item.replace(
        /^(\s*)([a-z][A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)(\s*)(?:\b(?:[Aa][Ss][Cc]|[Dd][Ee][Ss][Cc])\b)?(\s*)$/,
        (_m: string, lead: string, ident: string, mid: string, tail: string, dir?: string) =>
          dir
            ? `${lead}"${ident}"${mid}${dir.toUpperCase()}${tail}`
            : `${lead}"${ident}"${mid}${tail}`
      )
    )
    .map((item) => quoteCamelTokens(item))
    .join(", ");
}

/**
 * Quote bare camelCase identifiers anywhere in a clause item — including
 * qualified references (`alias.camelCase` → `alias."camelCase"`), window
 * function partition/order expressions (`PARTITION BY camelCase`,
 * `ORDER BY camelCase`), and nested subquery list items that were folded
 * into an outer body by quoteClauseRefs.
 *
 * A strict-camelCase token is one that starts lower-case, contains at least
 * one upper-case letter, and is bounded on both sides by a non-identifier
 * character (whitespace, comma, paren, operator, `.`). Tokens are skipped
 * when inside single/double-quoted string literals, backtick-quoted
 * identifiers, or already double-quoted identifiers. Fully-lower-case
 * columns and fully-upper-case function names/keywords are left untouched.
 */
function quoteCamelTokens(str: string): string {
  const out: string[] = [];
  let i = 0;
  const n = str.length;
  while (i < n) {
    const ch = str[i];
    // Skip string literals and quoted identifiers verbatim.
    if (ch === "'" || ch === '"' || ch === "`") {
      const q = ch;
      let j = i + 1;
      while (j < n && str[j] !== q) {
        if (str[j] === "\\") j++;
        j++;
      }
      out.push(str.slice(i, Math.min(j + 1, n)));
      i = Math.min(j + 1, n);
      continue;
    }
    // Match a strict-camelCase token at this position.
    if (/[a-z]/.test(ch)) {
      const m = /^([a-z][A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)/.exec(str.slice(i));
      if (m) {
        const ident = m[1];
        const before = i === 0 ? "" : str[i - 1];
        const after = str[i + ident.length];
        // Bounded: previous char is not an identifier char or `"`; next char
        // is not an identifier char. `.` is deliberately NOT excluded so the
        // qualified form `alias.camelCase` → `alias."camelCase"` is handled
        // (a `.` right before the camelCase token is fine). A camelCase
        // qualifier itself (`camelCaseColumn.col`) is left untouched because
        // the token is followed by `.`, which IS excluded on the right only
        // when it forms part of an identifier boundary — see below.
        const isBoundedBefore = !/[A-Za-z0-9_"']/.test(before);
        const isBoundedAfter = after === undefined || !/[A-Za-z0-9_".`]/.test(after);
        if (isBoundedBefore && isBoundedAfter) {
          out.push(`"${ident}"`);
          i += ident.length;
          continue;
        }
      }
    }
    out.push(ch);
    i++;
  }
  return out.join("");
}

/**
 * Quote bare camelCase identifiers in the SELECT list that are references to a
 * subquery alias. Splits on top-level commas (parens tracked so function calls
 * stay one item), then quotes exactly the items that are a single strict-
 * camelCase identifier. Function calls (e.g. `COUNT(*)`, `LOWER(p)`),
 * expressions, qualified names, `*`, lower-case columns, and quoted/cased
 * identifiers are preserved verbatim — so only the subquery-alias-reference
 * case (`SELECT dayOfWeek FROM (...) ...`) is touched, matching how
 * quoteGroupItems treats the GROUP BY / ORDER BY side.
 */
function quoteSelectList(rest: string): string {
  const parts: string[] = [];
  let depth = 0;
  let cur = "";
  for (const ch of rest) {
    if (ch === "(") depth++;
    else if (ch === ")") depth = Math.max(0, depth - 1);
    if (ch === "," && depth === 0) {
      parts.push(cur);
      cur = "";
    } else {
      cur += ch;
    }
  }
  parts.push(cur);
  // Per item: first try the whole item as a bare camelCase alias reference
  // (`executionKey`), then quote any remaining bare camelCase tokens inside
  // (qualified `alias.camelCase`, OVER(...) partition/order refs, nested
  // subquery list items that were folded into the body).
  return parts
    .map((item) =>
      item.replace(
        /^(\s*)([a-z][A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)(\s*)$/,
        (_m: string, lead: string, ident: string, tail: string) => `${lead}"${ident}"${tail}`
      )
    )
    .map((item) => quoteCamelTokens(item))
    .join(",");
}

/**
 * Rewrite SQLite NULL-safe `IS ?` / `IS NOT ?` to PostgreSQL equivalents.
 * SQLite's `IS` accepts an arbitrary right-hand operand, so `x IS ?` means
 * "x equals the param OR both are NULL". PostgreSQL's IS only accepts
 * NULL/TRUE/FALSE/UNKNOWN, so `x IS ?` would be a `syntax error at or near
 * "$N"`. Replace with `IS NOT DISTINCT FROM ?` / `IS DISTINCT FROM ?` to keep
 * identical semantics. Must run before rewritePlaceholders so the `?` still
 * receives its positional number (e.g. `scope_id IS $2` in the proxy layer).
 */
function rewriteIsParam(sql: string): string {
  return sql.replace(/\bIS\s+(NOT\s+)?\?/gi, (_m: string, notFlag: string | undefined) =>
    notFlag ? "IS DISTINCT FROM ?" : "IS NOT DISTINCT FROM ?"
  );
}

/**
 * Translate a PRAGMA query to an information_schema query.
 * Supported: PRAGMA table_info(<name>) — returns rows with the same shape
 * the SQLite pragma returns (cid, name, type, notnull, dflt_value, pk).
 */
export function pragmaToQuery(pragmaStr: string): { sql: string; params: unknown[] } | null {
  const m = /PRAGMA\s+table_info\s*\(\s*([^)]+)\s*\)/i.exec(pragmaStr.trim());
  if (!m) return null;
  const table = m[1].trim().replace(/^['"]|['"]$/g, "");
  return {
    sql: `
      SELECT
        ordinal_position - 1 AS cid,
        column_name AS name,
        CASE WHEN data_type IS NULL THEN '' ELSE data_type END AS type,
        CASE WHEN is_nullable = 'NO' THEN 1 ELSE 0 END AS notnull,
        COALESCE(column_default, '') AS dflt_value,
        CASE WHEN ordinal_position IN (
          SELECT kcu.ordinal_position
          FROM information_schema.table_constraints tc
          JOIN information_schema.key_column_usage kcu
            ON tc.constraint_name = kcu.constraint_name
           AND tc.table_schema = kcu.table_schema
          WHERE tc.table_name = $1
            AND tc.constraint_type = 'PRIMARY KEY'
        ) THEN 1 ELSE 0 END AS pk
      FROM information_schema.columns
      WHERE table_name = $1
      ORDER BY ordinal_position
    `,
    params: [table],
  };
}

/**
 * Translate a query against sqlite_master / sqlite_schema to a
 * information_schema query. Returns null when the query is not recognised.
 */
export function sqliteMasterToQuery(sql: string): { sql: string; params: unknown[] } | null {
  const m = /FROM\s+(?:sqlite_master|sqlite_schema)\b/i.exec(sql);
  if (!m) return null;
  const tail = sql.slice(m.index + m[0].length);
  const where = /\s+WHERE\s+(.*)$/is.exec(tail)?.[1] ?? "";
  // Typical patterns: WHERE type = 'table' / WHERE name = ? / WHERE tbl_name = ?
  let cond = "";
  const params: unknown[] = [];
  const typeM = /type\s*=\s*'([^']+)'/i.exec(where);
  if (typeM) cond += ` AND table_type = '${typeM[1].toUpperCase()}'`;
  const nameM = /(?:name|tbl_name)\s*=\s*(\?|\$?\d+)/i.exec(where);
  if (nameM) {
    cond += ` AND table_name = $1`;
    if (nameM[1].startsWith("$")) params.push(Number(nameM[1].slice(1)));
    else if (nameM[1] === "?") params.push(null); // filled by adapter param mapping
  }
  return {
    sql: `
      SELECT
        CASE WHEN table_type = 'VIEW' THEN 'view' ELSE 'table' END AS type,
        table_name AS name,
        table_name AS tbl_name,
        NULL AS rootpage,
        '' AS sql
      FROM information_schema.tables
      WHERE table_schema = 'public'${cond}
    `,
    params,
  };
}
